title: "ArtiPedia.Info"
description: "Artipedia.info adalah sumber informasi lengkap tentang definisi, tutorial, pendidikan, CPNS, airdrop, dan lebih banyak lagi. Temukan pengetahuan terbaru dan panduan praktis di dunia digital"
email: wahyu243@gmail.com
timezone: UTC
baseurl: ""
permalink: "/:title/"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
author: Wahyu243
paginate: 30
disqus: 'artipedia'
locale: id_id
lang: id_id
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: UA-113961478-1

# Authors
authors:
  sal:
    name: Wahyu243
    display_name: Wahyu243
    avatar: 'assets/images/wahyu243.png'
    email: wahyu243@gmail.com
    web: https://artipedia.info
    twitter: https://twitter.com/dobotcrypto
    description: "Senang tapi tidak mahir ngoding"
  john:
    name: John
    display_name: John
    avatar: 'assets/images/john.png'
    email: wowthemesnet@gmail.com
    web: https://www.wowthemes.net/category/jekyll-themes/
    twitter: https://twitter.com/wowthemesnet
    description: "This is the author box. Write a short description of the author here. You are currently previewing Affiliates theme demo, a Jekyll template compatible with Github pages."

# Social
social:
  instagram: https://www.instagram.com/bootstrapstarter/
  facebook: https://www.facebook.com/bootstrapstartercom-346329609045284
  twitter: https://twitter.com/bstartercom

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives
