title: "ArtiPedia.Info"
description: "Artipedia.info adalah sumber informasi lengkap tentang definisi, tutorial, pendidikan, CPNS, airdrop, dan lebih banyak lagi. Temukan pengetahuan terbaru dan panduan praktis di dunia digital"
email: wahyu243@gmail.com
timezone: UTC
baseurl: ""
permalink: "/:title/"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
author: Wahyu243
paginate: 30
disqus: 'artipedia'
locale: id_id
lang: id_id
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: G-VL29CY397R

- scope:
    path: _posts/airdrop
    type: posts
  values:
    layout: post
    category: Airdrop
    csymb: airdrop
    permalink: "/airdrop/:title"
    image: twitter-card.png
    author: wahyu243
    avatar: /asset/image/wahyu243.jpg
    read_time: true
    comments: true
    support: true
    breadcrumbs:
      - label: "Airdrop"
        url: /airdrop
        
# Authors
authors:
  wahyu243:
    name: Wahyu243
    display_name: Wahyu243
    avatar: 'assets/images/wahyu243.jpg'
    email: wahyu243@gmail.com
    web: https://artipedia.info
    twitter: https://twitter.com/dobotcrypto
    description: "Hpbi tapi tidak mahir ngoding"
  john:
    name: John
    display_name: John
    avatar: 'assets/images/john.png'
    email: wowthemesnet@gmail.com
    web: https://www.wowthemes.net/category/jekyll-themes/
    twitter: https://twitter.com/wowthemesnet
    description: "This is the author box. Write a short description of the author here. You are currently previewing Affiliates theme demo, a Jekyll template compatible with Github pages."

# Social
social:
  instagram: https://www.instagram.com/artipedia.info
  facebook: https://www.facebook.com/artipedia.info
  twitter: https://twitter.com/artipedia.info

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives
